name: Build/release

on: 
  push:
    branches: [main]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm install

      - name: Build/release Electron app
        env:
          GH_TOKEN: ${{ github.token }}
        run: npm run build -- --publish always --mac --win --x64